version: "3.7"

services:
  geth:
    container_name: geth
    restart: unless-stopped
    image: ethereum/client-go:v1.10.25
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8545:8545
      - 8551:8551
      # - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    command: >
      --datadir /home/geth
      --http
      --http.addr "0.0.0.0"
      --http.vhosts "*"
      --http.corsdomain "*"
      --http.api="db,eth,net,web3,personal"
      --allow-insecure-unlock
      --ws
      --ws.addr "0.0.0.0"
      --http.corsdomain "*"
      --ws.origins "*"
      --nousb
      --cache=8096
      --maxpeers=200
      --syncmode=snap
      --gpo.percentile=75
      --authrpc.vhosts="*"
      --authrpc.addr="0.0.0.0"
      --authrpc.port=8551
      --authrpc.jwtsecret=/home/jwtsecret_mainnet.hex
      --mainnet
    volumes:
      - ${DIR}/mainnet/geth:/home/geth
      - ./jwtsecret_mainnet.hex:/home/jwtsecret_mainnet.hex:ro
    networks:
      infura:
        ipv4_address: 10.2.0.101

  prysm:
    container_name: beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v3.1.1
    restart: always
    hostname: beacon-chain
    depends_on:
            - geth
    command: >
      --datadir="/home/prysm"
      --accept-terms-of-use=true
      --http-web3provider="http://geth:8551"
      --rpc-host="0.0.0.0"
      --p2p-host-ip=""
      --p2p-host-dns=""
      --p2p-tcp-port=13000
      --p2p-max-peers=200
      --jwt-secret=/home/jwtsecret_mainnet.hex
      --grpc-gateway-host="0.0.0.0"
      --grpc-gateway-port=3500
      --mainnet
    ports:
      - 4000:4000
      - 3500:3500
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - ${DIR}/mainnet/prysm:/home/prysm
      - ./jwtsecret_mainnet.hex:/home/jwtsecret_mainnet.hex:ro
      - ./jwtsecret_mainnet.ssz:/home/jwtsecret_mainnet.ssz:ro
    networks:
      infura:
        ipv4_address: 10.2.0.104

  bitcoind:
    container_name: bitcoind
    restart: unless-stopped
    image: kylemanna/bitcoind@sha256:b4e1c7e5c3e51557a625c053c875c0ee69f88a51a92f21b6f7b71b0f3cc6f6cc
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    # - 8332:8332
      - 8333:8333
    volumes:
      - ${DIR}/mainnet/bitcoind/.bitcoin:/bitcoin/.bitcoin
    command: >
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -minrelaytxfee=0
      -maxmempool=300
      -mempoolexpiry=12
      -rpcworkqueue=600
      -txindex=1
      -rpcuser=bitcoinrpc
      -rpcpassword=80vDUBXVMS4zH4Z+KjmBQuhKefsh0qNrBvM4G+ry0/48
    networks:
      infura:
        ipv4_address: 10.2.0.102

  bsc:
    container_name: bsc
    restart: unless-stopped
    image: swingbylabs/bsc:1.1.8
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8575:8575
    # - 8576:8576
      - 30311:30311
      - 30311:30311/udp
    volumes:
      - ${DIR}/mainnet/bsc:/home/geth
    command: >
      --config /home/geth/config.toml
      --datadir /home/geth/data
      --syncmode=snap
      --cache 8096
      --txlookuplimit 1600000
      --http
      --http.addr "0.0.0.0"
      --http.corsdomain "*"
      --http.port "8575"
      --http.vhosts "*"
      --ws
      --ws.addr "0.0.0.0"
      --ws.port "8576"
      --ws.origins "0.0.0.0"
      --diffsync
    networks:
      infura:
        ipv4_address: 10.2.0.103

  bb_btc:
    container_name: bb_btc_mainnet
    restart: unless-stopped
    build: ../../blockbooks/bitcoin/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
     #- 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/mainnet/bb_bitcoin:/opt/coins/blockbook/bitcoin/data
    networks:
      infura:
        ipv4_address: 10.2.0.111

  bb_eth:
    container_name: bb_eth_mainnet
    restart: unless-stopped
    build: ../../blockbooks/ethereum/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      # - 9031:9030
      # - 9131:9130
      - 9130:9130
    volumes:
      - ${DIR}/mainnet/bb_eth:/opt/coins/blockbook/ethereum/data
    networks:
      infura:
        ipv4_address: 10.2.0.112

  bb_bsc:
    container_name: bb_bsc_mainnet
    restart: unless-stopped
    build: ../../blockbooks/bsc/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9032:9030
      - 9132:9130
    volumes:
      - ${DIR}/mainnet/bb_bsc:/server/coins/blockbook/bsc/data
    networks:
      infura:
        ipv4_address: 10.2.0.113

networks:
  infura:
    name: infura
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
