version: "3.7"

services:
  geth:
    container_name: geth
    restart: unless-stopped
    image: ethereum/client-go:stable
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8545:8545
    # - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - ${DIR}/mainnet/geth:/home/geth
    command: >
      --datadir /home/geth 
      --http 
      --http.addr "0.0.0.0" 
      --ws 
      --ws.addr "0.0.0.0" 
      --http.corsdomain "*" 
      --ws.origins "*" 
      --nousb
      --cache=4096
      --maxpeers=200
      --syncmode=fast
    networks:
      infura:
        ipv4_address: 10.2.0.101

  bitcoind:
    container_name: bitcoind
    restart: unless-stopped
    image: kylemanna/bitcoind
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    # - 8332:8332
      - 8333:8333
    volumes:
      - ${DIR}/mainnet/bitcoind/.bitcoin:/bitcoin/.bitcoin
    command: >
      -rpcbind=0.0.0.0 
      -rpcallowip=0.0.0.0/0 
      -minrelaytxfee=0 
      -maxmempool=300 
      -mempoolexpiry=10 
      -rpcworkqueue=600 
      -txindex=1 
      -disablewallet=1
      -rpcuser=bitcoinrpc
      -rpcpassword=80vDUBXVMS4zH4Z+KjmBQuhKefsh0qNrBvM4G+ry0/48
    networks:
      infura:
        ipv4_address: 10.2.0.102

  bb_btc:
    container_name: bb_btc_mainnet
    restart: unless-stopped
    build: ../../blockbooks/bitcoin/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
     #- 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/mainnet/bb_bitcoin:/opt/coins/blockbook/bitcoin/data
    networks:
      infura:
        ipv4_address: 10.2.0.103

  bb_eth:
    container_name: bb_eth_mainnet
    restart: unless-stopped
    build: ../../blockbooks/ethereum/mainnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    # - 9031:9030
      - 9131:9130
    volumes:
      - ${DIR}/mainnet/bb_eth:/opt/coins/blockbook/ethereum/data
    networks:
      infura:
        ipv4_address: 10.2.0.104

networks:
  infura:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
