version: "3.7"

services:
  geth:
    container_name: geth_goerli
    restart: unless-stopped
    image: ethereum/client-go:v1.10.21
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8545:8545
      - 8551:8551
    # - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    command: >
      --datadir /home/geth 
      --http 
      --http.addr "0.0.0.0" 
      --http.vhosts "*"
      --http.corsdomain "*" 
      --http.api="db,eth,net,web3,personal"
      --allow-insecure-unlock
      --ws 
      --ws.addr "0.0.0.0" 
      --ws.origins "*" 
      --nousb
      --cache=8096
      --maxpeers=200
      --syncmode=snap
      --gpo.percentile=75
      --authrpc.vhosts="*"
      --authrpc.addr="0.0.0.0"
      --authrpc.port=8551
      --authrpc.jwtsecret=/home/jwtsecret_goerli.hex
      --goerli
    volumes:
      - ${DIR}/testnet/geth:/home/geth
      - ./jwtsecret_goerli.hex:/home/jwtsecret_goerli.hex:ro
    networks:
      infura:
        ipv4_address: 10.2.0.101
  prysm:
    container_name: beacon-chain
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.1.4-rc.0
    restart: always
    hostname: beacon-chain
    depends_on:
            - geth
    command: >
      --datadir="/home/prysm"
      --accept-terms-of-use=true
      --http-web3provider="http://geth:8551"
      --rpc-host="0.0.0.0"
      --p2p-host-ip=""
      --p2p-host-dns=""
      --p2p-tcp-port=13000
      --p2p-max-peers=200
      --jwt-secret=/home/jwtsecret_goerli.hex
      --genesis-state=/home/genesis_goerli.ssz
      --grpc-gateway-host="0.0.0.0"
      --grpc-gateway-port=3500
      --goerli
    ports:
      - 4000:4000
      - 3500:3500
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - ${DIR}/testnet/prysm:/home/prysm
      - ./jwtsecret_goerli.hex:/home/jwtsecret_goerli.hex:ro
      - ./genesis_goerli.ssz:/home/genesis_goerli.ssz:ro
    networks:
      infura:
        ipv4_address: 10.2.0.104
  bitcoind:
    container_name: bitcoind_testnet
    restart: unless-stopped
    image: kylemanna/bitcoind@sha256:b4e1c7e5c3e51557a625c053c875c0ee69f88a51a92f21b6f7b71b0f3cc6f6cc
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
    # - 18332:18332
      - 18333:18333
    volumes:
      - ${DIR}/testnet/bitcoind:/bitcoin/.bitcoin
    command: >
      -rpcbind=0.0.0.0 
      -rpcallowip=0.0.0.0/0 
      -minrelaytxfee=0 
      -maxmempool=300 
      -mempoolexpiry=12 
      -rpcworkqueue=700
      -txindex=1
      -rpcuser=bitcoinrpc
      -rpcpassword=80vDUBXVMS4zH4Z+KjmBQuhKefsh0qNrBvM4G+ry0/48
      -testnet=1
    networks:
      infura:
        ipv4_address: 10.2.0.102
  bsc:
    container_name: bsc_testnet
    restart: unless-stopped
    image: swingbylabs/bsc:1.1.7
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8575:8575
   #  - 8576:8576
      - 30311:30311
      - 30311:30311/udp
    volumes:
      - ${DIR}/testnet/bsc_testnet:/home/geth
    command: >
      --config /home/geth/config.toml
      --datadir /home/geth/data
      --syncmode=snap
      --http 
      --http.addr "0.0.0.0"
      --http.corsdomain "*" 
      --http.port "8575"
      --http.vhosts "*"
      --ws
      --ws.addr "0.0.0.0"
      --ws.port "8576" 
      --ws.origins "0.0.0.0"
    networks:
      infura:
        ipv4_address: 10.2.0.103

  bb_btc:
    container_name: bb_btc_testnet
    restart: unless-stopped
    build: ../../blockbooks/bitcoin/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/testnet/bb_bitcoin:/opt/coins/blockbook/bitcoin_testnet/data
    networks:
      infura:
        ipv4_address: 10.2.0.111

  bb_eth:
    container_name: bb_eth_testnet
    restart: unless-stopped
    build: ../../blockbooks/ethereum/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/testnet/bb_eth:/opt/coins/blockbook/ethereum_testnet_goerli/data
    networks:
      infura:
        ipv4_address: 10.2.0.112

  bb_bsc:
    container_name: bb_bsc_testnet
    restart: unless-stopped
    build: ../../blockbooks/bsc/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9032:9030
      - 9132:9130
    volumes:
      - ${DIR}/testnet/bb_bsc:/server/coins/blockbook/bsc_testnet/data
    networks:
      infura:
        ipv4_address: 10.2.0.113

  bb_dcn:
    container_name: bb_dcn_testnet
    restart: unless-stopped
    build: ../../blockbooks/dcn/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/testnet/bb_dcn:/opt/coins/blockbook/iochain_testnet/data
    networks:
      infura:
        ipv4_address: 10.2.0.114

networks:
  infura:
    name: infura
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
