version: "3.7"

services:
  geth:
    container_name: geth_goerli
    restart: unless-stopped
    image: ethereum/client-go:stable
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp
    volumes:
      - ${DIR}/testnet/geth_goerli:/home/geth
    command: >
      --datadir /home/geth 
      --http 
      --http.addr "0.0.0.0" 
      --ws 
      --ws.addr "0.0.0.0" 
      --http.corsdomain "*" 
      --ws.origins "10.2.0.104" 
      --nousb 
      --goerli
    networks:
      infura:
        ipv4_address: 10.2.0.101

  bitcoind:
    container_name: bitcoind_testnet
    restart: unless-stopped
    image: kylemanna/bitcoind
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 18332:18332
      - 18333:18333
    volumes:
      - ${DIR}/testnet/bitcoind:/bitcoin
    command: >
      -rpcbind=0.0.0.0 
      -rpcallowip=0.0.0.0/0 
      -minrelaytxfee=0 
      -maxmempool=300 
      -mempoolexpiry=10 
      -rpcworkqueue=200 
      -txindex=1 
      -disablewallet=0 
      -rpcuser=bitcoinrpc
      -rpcpassword=80vDUBXVMS4zH4Z+KjmBQuhKefsh0qNrBvM4G+ry0/48
      -testnet=1
    networks:
      infura:
        ipv4_address: 10.2.0.102
    
  bb_btc:
    container_name: bb_btc_testnet
    restart: unless-stopped
    build: ../../blockbooks/bitcoin/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9030:9030
      - 9130:9130
    volumes:
      - ${DIR}/testnet/bb_bitcoin:/opt/coins/blockbook/bitcoin_testnet/data
    networks:
      infura:
        ipv4_address: 10.2.0.103

  bb_eth:
    container_name: bb_eth_testnet
    restart: unless-stopped
    build: ../../blockbooks/ethereum/testnet
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9031:9030
      - 9131:9130
    volumes:
      - ${DIR}/testnet/bb_eth:/opt/coins/blockbook/ethereum_testnet_goerli/data
    networks:
      infura:
        ipv4_address: 10.2.0.104

networks:
  infura:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
